# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python scripts
COPY src/python-scripts /app/python-scripts

# Set the command to keep the container running
CMD ["tail", "-f", "/dev/null"]
