version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - python-app

  python-app:
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - .:/app
