/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BwVZiv8JZLn
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Stems } from "./stems";
import Upload from "./upload";

export function FileUpload() {
  return (
    <div className="flex flex-col">
      <div className="flex flex-col items-center justify-center bg-background">
        <div className="w-full py-12 md:py-16">
          <Upload
            title="Audio Stem Separation"
            description="Upload your audio file and let our AI separate it into individual stems."
          />
          <Stems />
        </div>
      </div>
    </div>
  );
}
