/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/G5uWGKQ3byc
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Progress } from "@/components/ui/progress";
import {
  DownloadIcon,
  MenuIcon,
  MicIcon,
  Music2Icon,
  PlayIcon,
  UploadIcon,
} from "./icons";
import Upload from "./upload";

export function VocalRemover() {
  return (
    <div className="flex flex-col">
      <div className="flex flex-col items-center justify-center bg-background">
        <div className="w-full py-12 md:py-16">
          <Upload
            title="Vocal Remover"
            description="Upload your audio file and let our AI remove the vocals."
          />
          <div className="flex flex-col items-start">
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-primary">
              Vocal-Removed Audio
            </h2>
            <p className="text-muted-foreground text-lg mb-8">
              Listen to or download the vocal-removed audio, as well as the
              remaining music.
            </p>
            <div className="w-full bg-muted rounded-lg p-6 border">
              <div className="flex items-center mb-4">
                <MicIcon className="w-6 h-6 mr-2 text-primary" />
                <h3 className="text-lg font-medium">Vocal-Removed Audio</h3>
                <div className="ml-auto flex items-center gap-2">
                  <Button variant="ghost" size="icon">
                    <PlayIcon className="w-5 h-5" />
                  </Button>
                  <Button variant="ghost" size="icon">
                    <DownloadIcon className="w-5 h-5" />
                  </Button>
                </div>
              </div>
              <Progress value={90} className="mb-4" />
              <div className="flex items-center mb-4">
                <Music2Icon className="w-6 h-6 mr-2 text-primary" />
                <h3 className="text-lg font-medium">Remaining Music</h3>
                <div className="ml-auto flex items-center gap-2">
                  <Button variant="ghost" size="icon">
                    <PlayIcon className="w-5 h-5" />
                  </Button>
                  <Button variant="ghost" size="icon">
                    <DownloadIcon className="w-5 h-5" />
                  </Button>
                </div>
              </div>
              <Progress value={80} className="mb-4" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
